spirng:
    profiles:
          active:
          - dev
---
spring:
     profiles:  dev
     application:
             name: microservicecloud-config-atguigu-dev
---
spirng:
    profiles: test
    application:
            name: microservicecloud-config-atguigu-test